### ISSUE TITLE
How to Download the generated image?

### ISSUE THREAD

**Issue by shreshthasarkar** [saurabhdaware/text-to-handwriting#11]

**Comment by saurabhdaware** [comment]
![Screenshot of output showing download button below the output div](https://user-images.githubusercontent.com/30949385/79856220-b07fb700-83e9-11ea-9343-0dbd1658f05d.png)
There's a download button below the output.

 I've tested this on desktop (chrome) and android chrome let me know if it is not visible in your device

**Comment by shreshthasarkar** [comment]
Yeah the download button is not visible.
![Screen Shot 2020-04-21 at 4 12 28 PM](https://user-images.githubusercontent.com/32956309/79857141-f426f080-83ea-11ea-87ed-60d5174bec99.png)

**Comment by saurabhdaware** [comment]
oh, it will come after clicking the "generate image" button above textarea. The generate button will add some extra effects and will put a background of a paper and after that you can download

**Comment by shreshthasarkar** [comment]
![Screen Shot 2020-04-21 at 4 21 22 PM](https://user-images.githubusercontent.com/32956309/79857938-2edd5880-83ec-11ea-9065-2cf846de72d8.png)
So if I'm copy pasting this is happening.

**Comment by saurabhdaware** [comment]
Yes, currently you have to paste it as a plain text to remove the existing styles of content. I had fixed this in earlier versions but had to roll back because it removed the line breaks as well. 

Ctrl + shift + V should work for now. I'll try to see if there's any way out to paste as plain text by default while keeping the line-breaks.

Also, is download button visible now?
