### ISSUE TITLE
Minor improve in UI for mobile responsive

### ISSUE THREAD

**Issue by mohananagavenkat** [saurabhdaware/text-to-handwriting#56]
Hi @saurabhdaware, 

I just saw the tweet and came here. Nice work 👏 .

There is a minor alignment issue while visiting the app from a mobile device. Below is the screenshot.

![text to image](https://user-images.githubusercontent.com/30862450/85929868-c1f7aa80-b8d5-11ea-93ac-8164a7f53c8a.PNG)

There is a simple fix - by using CSS white-space property. Below is the screenshot after the fix.

![text to image after fix](https://user-images.githubusercontent.com/30862450/85929936-29155f00-b8d6-11ea-8c4e-75f340d515de.PNG)

**Comment by saurabhdaware** [comment]
Uh oh definitely a bug, thank you for reporting! 

but adding white-space may push the content out of the viewport in some mobiles,

Here's a screenshot from my mobile:
![Screenshot of tool from mobile that shows adding white space pushed the content to the right and a word is not completely visible because of that](https://user-images.githubusercontent.com/30949385/85940164-690d2e00-b938-11ea-969b-23539ee423ff.png)

Let's see if we can do something else, I'll keep this open for anyone who wants to contribute :D

**Comment by RinkiyaKeDad** [comment]
Has this issue been solved? Because it seems to be correct when I see it in mobile view?
![WriteCapture](https://user-images.githubusercontent.com/56963264/86238959-16dc3f00-bbbc-11ea-8325-7a2c89576b66.JPG)

**Comment by saurabhdaware** [comment]
Oh yes I didn't realize #57 added new UI so it fixed this.
