### ISSUE TITLE
Display total number of pages

### ISSUE THREAD

**Issue by Eronmmer** [saurabhdaware/text-to-handwriting#66]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Just a little badge or something above or below the "Page Output" section to display the total number of pages to be printed.

**Comment by saurabhdaware** [comment]
Oh yes that makes sense, Thank you for pointing it out! 

We can have it beside the "Output" heading. I am keeping this open if someone wants to work on it. 

In the file [src/generate-images.mjs](https://github.com/saurabhdaware/text-to-handwriting/blob/master/js/generate-images.mjs), there's an array called `outputImages` which contains all the output images so that array's length will be total number of pages.
